"""init.

Revision ID: ba6950c11b56
Revises:
Create Date: 2026-07-13 11:39:07.843887

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ba6950c11b56"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
