"""init.

Revision ID: 3b17c1999a54
Revises:
Create Date: 2026-07-13 18:25:40.114639

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3b17c1999a54"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
